const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  orientation: state => state.globalvar.orientation,
  tokenStr: state => state.globalvar.tokenStr,
  avatar: state => state.globalvar.profilepic,
  locations: state => state.info.locations,
  equiptype: state => state.info.equiptype,
  equiptypeall: state => state.info.equiptypeall,
  loadingmainpage: state => state.info.loadingmainpage,

  bottombuttom: state => state.chatbot.bottombuttom,
  g_tags: state => state.chatbot.g_tags,
  stat_qna: state => state.chatbot.g_qna,
  deSelectClick: state => state.chatbot.bottombuttom.deSelectClick,
  dialogEdit: state => state.chatbot.bottombuttom.dialogEdit,
  dialog_editAns: state => state.chatbot.dialog_editAns,
  mergeIntentClick: state => state.chatbot.bottombuttom.mergeIntentClick,
  sel_intent: state => state.chatbot.selectedIntentVux,
  flag_addAnswer: state => state.chatbot.flag.fg_addAnswer,
  thday: state => state.chatbot.thday,
  thmonth: state => state.chatbot.thmonth,
  meetting: state => state.chatbot.meetting,
  statusLogin: state => state.chatbot.statusLogin,
  usermenu: state => state.chatbot.usermenu,
  gImg:state => state.chatbot.gImg,
  g_dialog:state => state.chatbot.g_dialog,
  configfile: state => state.chatbot.configfile,
  restserver: state => state.chatbot.restserver,
  selectSpeedDail: state => state.chatbot.selectSpeedDail,
  bottombuttom: state => state.chatbot.bottombuttom,
  question_q: state => state.chatbot.question_q,
  edit_setting: state => state.chatbot.edit_setting,
  dialogEditans: state => state.chatbot.dialogEditans,
  x_stk_list: state => state.chatbot.stk_list

  //server: state => state.globalvar.server
}
export default getters
